
[project]
name = "lompeosse"
version = "0.0.0"
description = "Toolbox for evaluating Lompe ionospheric electrodynamics reconstruction using synthetic Gamera data in Observation System Simulation Experiments."
authors = [
    { name = "Margot Decotte, Karl Laundal", email = "margot.decotte@uib.no" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "apexpy",
    "matplotlib",
    "numpy",
    "pandas",
    "h5py",
    "tables",
    "PyYAML",
    "ppigrf",
    "pyhdf",
    "dipole @ git+https://github.com/klaundal/dipole.git",
    "lompe @ git+https://github.com/klaundal/lompe.git",
    "polplot @ git+https://github.com/klaundal/polplot.git",
    "secsy @ git+https://github.com/klaundal/secsy.git",
]

#- scipy
#- xarray
#- `astropy <https://github.com/astropy/astropy/>`_ (if you use the AMPERE Iridium data preprocessing scripts)
#- `cdflib <https://github.com/MAVENSDC/cdflib/>`_ (for running lompe paper figures example 05)
#- `madrigalWeb <https://pypi.org/project/madrigalWeb/>`_ (if you use the DMSP SSIES data preprocessing scripts)
#- `netCDF4 <https://github.com/Unidata/netcdf4-python/>`_ (if you use the DMSP SSUSI data preprocessing scripts)
#- `pyAMPS <https://github.com/klaundal/pyAMPS/>`_ (for running code paper figures example 08)
#- `pydarn <https://github.com/SuperDARN/pydarn/>`_ (if you use the SuperDARN data preprocessing scripts)

[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
lompeosse = ["data/*"]


#[project.scripts]
#swarmdf = "swarmdf.cli.main:main"
#swarmdf-gui = "swarmdf.gui.app:main"